### ISSUE TITLE
The purpose of the setTimeout.

### ISSUE THREAD

**Issue by ashclarke** [addyosmani/pubsubz#1]
Hi Addy, quick question - What is the reason for the zero-length timeout on line 21 (https://github.com/addyosmani/pubsubz/blob/master/pubsubz.js#L21), surrounding the calls for each subscriber?

**Comment by boban100janovski** [comment]
Because duration is set to 0, I suppose it would remove the code in the setTimeout from the flow of execution. 
If u have some code that takes some time to execute it would not prevent subsequent code from executing.

**Comment by ashclarke** [comment]
Thanks!

**Comment by RinatMullayanov** [comment]
As far as I know the function, delayed through the setTimeout (.. 0) is executed on or after the next "tick" timer, the minimum frequency of which may be from 4 to 1000ms. 
In my best to use setImmediate http://msdn.microsoft.com/en-us/library/ie/hh773176.aspx (and emulation for browsers other than IE based postMessage)
